#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Copyright 2025 Peter Tribble
#

PATH=/usr/jdk/instances/jdk11/bin:$PATH
export PATH

#
# new PMD version has categories only, configured in pmd-ruleset.xml
#
PMDRULES="./pmd-ruleset.xml"
PMDCACHE="${HOME}/.pmd/cache.pctgemini"

JARLIBDIR=lib/java
JINGLEJAR=${JARLIBDIR}/jingle.jar
JUMBLEJAR=${JARLIBDIR}/jumble.jar
BUILDJARS=${JINGLEJAR}:${JUMBLEJAR}

case $1 in
clean)
	rm -f $(find . -name '*.class')
	rm -f $(find . -name '*~')
	rm -fr javadoc
	exit 0
	;;
package)
	./pkg/mkproto > pp
	pkgmk -d /tmp -f pp -r $(pwd) TRIBpctgemini
	pkgtrans -s /tmp /tmp/TRIBpctgemini.pkg TRIBpctgemini
	rm -fr /tmp/TRIBpctgemini
	ls -l /tmp/TRIBpctgemini.pkg 
	rm pp
	exit 0
	;;
javadoc)
	rm -fr javadoc
	mkdir javadoc
	javadoc -classpath "$BUILDJARS:." -Xdoclint:all -d javadoc uk.co.petertribble.pctgemini.{gui,network}
	exit 0
	;;
pmd)
	if [ ! -d "${HOME}/.pmd" ]; then
	    mkdir -p "${HOME}/.pmd"
	fi
	pmd check --cache "${PMDCACHE}" -d uk -R "${PMDRULES}" --use-version java-11 --aux-classpath $(echo lib/java/* | sed 's= =:=g') 2>/dev/null
	exit 0
	;;
spotbugs)
	#
	# spotbugs works on the class files, so those need to be available
	#
	javac -Xlint -classpath ".:${BUILDJARS}" uk/co/petertribble/pctgemini/*/*.java
	spotbugs -auxclasspath $(echo lib/java/* | sed 's= =:=g') uk
	rm -f $(find uk -name '*.class')
	exit 0
	;;
esac

javac -Xlint -classpath ".:${BUILDJARS}" uk/co/petertribble/pctgemini/*/*.java
jar cmf pctgemini.manifest lib/java/pctgemini.jar $(find uk -name '*.class')
rm -f $(find uk -name '*.class')
