version = 1

[[annotations]]
path = [ "README.md", "pctgemini.manifest", "lib/java/jingle.jar", "lib/java/jumble.jar", "lib/java/pctgemini.jar" ]
SPDX-FileCopyrightText = "2025 Peter Tribble"
SPDX-License-Identifier = "CDDL-1.0"
